### ISSUE TITLE
Cannot using

### ISSUE THREAD

**Issue by iVoGia** [bastienFalcou/VideoScreenRecorder#7]
Hello top,
I cannot use your library, 
It's show with error:
Error occured, status = 3, Không thể lưu Optional(Error Domain=AVFoundationErrorDomain Code=-11823 "Cannot Save" UserInfo={NSLocalizedRecoverySuggestion=., NSLocalizedDescription=NSUnderlyingError=0x283e60570 {Error Domain=NSOSStatusErrorDomain Code=-12412 "(null)"}})

Please help me how to fix it. 

Thanks

**Comment by fukemy** [comment]
how did u fixed this?
